version: '3.3'

services:
   db:
     container_name: "wordpress_db"
     image: mariadb
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: 6JCcDEx%G7s8qXL5
       MYSQL_DATABASE: wordpress_wp
       MYSQL_USER: admin
       WORDPRESS_DB_PASSWORD: wAQXKMy7=4G7vQQa

   wp:
     container_name: "wordpress"
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - "8000:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_NAME: wordpress_wp
       WORDPRESS_DB_USER: root
       WORDPRESS_DB_PASSWORD: 6JCcDEx%G7s8qXL5
     volumes: 
       - ./wp-content:/var/www/html/wp-content/ #NECESSARY IF YOU WANT TO MOUNT YOUR PLUGIN 
       - ./react-plugin-wp:/var/www/html/wp-content/plugins/react-plugin-wp #MOUNT YOUR PLUGIN
volumes:
    db_data: {}
